spring:
  application:
    name: user-onboarding
  profiles:
    active: ${ACTIVE_PROFILE:home}
server:
  port: 9091
  servlet:
    context-path: /onboarding-api
app:
  version: 10046


---
spring:
  profiles: home
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  h2:
    console:
      enabled: true
  kafka:
    producer:
      bootstrap-servers: localhost:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


